language: python
python:
  - "3.2"
  - "3.3"
env:
  - NUMPYSPEC=
  - NUMPYSPEC===1.8.0
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran hdf5-tools libhdf5-serial-dev
  - pip install cython
  - pip install numpy$NUMPYSPEC
  - pip install scipy
  - pip install matplotlib
  - pip install h5py
  - pip install coverage coveralls
# command to run tests, e.g. python setup.py test
script:  nosetests --with-coverage
# check coverage
after_success:
  - coveralls