language: python
matrix:
  include:
    - python: 3.2
      env:
        - NUMPYSPEC===1.8.0
        - SCIPYSPEC===0.13.0
        - MATPLOTLIBSPEC===1.3.1
    - python: 3.3
      env:
        - NUMPYSPEC=
        - SCIPYSPEC=
        - MATPLOTLIBSPEC=
    - python: 3.4
      env:
        - NUMPYSPEC=
        - SCIPYSPEC=
        - MATPLOTLIBSPEC=
# install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran hdf5-tools libhdf5-serial-dev
  - travis_wait pip install numpy$NUMPYSPEC
  - travis_wait pip install scipy$SCIPYSPEC
  - travis_wait pip install matplotlib$MATPLOTLIBSPEC
  - pip install h5py
  - pip install coverage coveralls
# run tests (select a proper matplotlib backend)
before_script: echo "backend : Agg" > matplotlibrc
script:  nosetests --with-doctest --with-coverage
# check coverage
after_success:
  - coveralls
